# This file is auto generated by VP
# Script on Node {869d30fb-c218-46dc-a254-87c260845f8f}
# VPValueDict structure: {"_CLASS_": DataType, "data": Value(dict)}
# supported DataType set is {
# 	'Int', 'Bool', 'Double', 'String', 
# 	'IntList', 'DoubleList', 'StringList', 
# 	'GraspPlans', 'PickPlan', 
# 	'PickPlacePlanPairs','PickPlacePlanPair', 
# 	'ObjectPlacePoses', 'FlangePoses', 
# 	'SKUInfoData', 'SKUInfoList', 
# 	'MixPalletizeSKUInfoData', 'MixPalletizeSKUInfoList', 
# 	'Trajectory', 'VPJointData', 
# 	'VPNodeError', 
# 	'CartPose', 'Json'} 
# Following Functions can be called:
#   get_input(port_index) -> Value
#   get_input_by_key(key) -> Value
#   set_output(port_index, Value/ValueDict)
#   set_logic_outcome(port_index)
#   read_gv(name) -> ValueDict
#   write_gv(name, Value, DataType)
#   write_gv(name, ValueDict)
#   clear_gv(name)
#   new(DataType, Value) -> ValueDict
#   reg_sys_path(Path)
# Do not call input() to get input data
# Runtime Error Will be catched by vp_python_base

def run():
  print('Hello World')