"""V1.2.0: 修改 log 表中的 message 字段长度

Revision ID: 838f4ce50379
Revises: a5509a75ac8e
Create Date: 2022-07-04 10:09:07.307006

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '838f4ce50379'
down_revision = 'a5509a75ac8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'log', 'zh_msg',
        existing_type=mysql.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=True
    )
    op.alter_column(
        'log', 'en_msg',
        existing_type=mysql.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=True
    )
    op.alter_column(
        'log', 'ja_msg',
        existing_type=mysql.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=True
    )
    op.alter_column(
        'log', 'zh_tip',
        existing_type=mysql.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=True
    )
    op.alter_column(
        'log', 'en_tip',
        existing_type=mysql.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=True
    )
    op.alter_column(
        'log', 'ja_tip',
        existing_type=mysql.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'log', 'ja_tip',
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=100),
        existing_nullable=True
    )
    op.alter_column(
        'log', 'en_tip',
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=100),
        existing_nullable=True
    )
    op.alter_column(
        'log', 'zh_tip',
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=100),
        existing_nullable=True
    )
    op.alter_column(
        'log', 'ja_msg',
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=100),
        existing_nullable=True
    )
    op.alter_column(
        'log', 'en_msg',
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=100),
        existing_nullable=True
    )
    op.alter_column(
        'log', 'zh_msg',
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=100),
        existing_nullable=True
    )
    # ### end Alembic commands ###
