"""V1.2.0: register_box 新增 `normal_length`, `normal_width`, `normal_height` 字段

Revision ID: a4aa5a61530c
Revises: fedf33da39ff
Create Date: 2022-07-04 15:18:49.112929

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a4aa5a61530c'
down_revision = 'fedf33da39ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dpt_map_box_create_time', table_name='dpt_register_box')
    op.drop_index('ix_dpt_map_box_update_time', table_name='dpt_register_box')
    op.create_index(
        op.f('ix_dpt_register_box_create_time'),
        'dpt_register_box',
        ['create_time'],
        unique=False
    )
    op.create_index(
        op.f('ix_dpt_register_box_update_time'),
        'dpt_register_box',
        ['update_time'],
        unique=False
    )
    op.create_unique_constraint(
        'uniq_normal_l_w_h',
        'dpt_register_box',
        ['normal_length', 'normal_width', 'normal_height', 'is_del']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_normal_l_w_h', 'dpt_register_box', type_='unique')
    op.drop_index(
        op.f('ix_dpt_register_box_update_time'),
        table_name='dpt_register_box'
    )
    op.drop_index(
        op.f('ix_dpt_register_box_create_time'),
        table_name='dpt_register_box'
    )
    op.create_index(
        'ix_dpt_map_box_update_time',
        'dpt_register_box',
        ['update_time'],
        unique=False
    )
    op.create_index(
        'ix_dpt_map_box_create_time',
        'dpt_register_box',
        ['create_time'],
        unique=False
    )
    # ### end Alembic commands ###
