"""V1.2.0: design 新增 `guillotine_packing`, `barcode_direction`, `mirror`, `flip`, `layers` 字段

Revision ID: 2c2a6d1c7e0c
Revises: a4aa5a61530c
Create Date: 2022-07-05 09:34:26.902128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c2a6d1c7e0c'
down_revision = 'a4aa5a61530c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design', sa.Column('guillotine_packing', sa.Integer(), nullable=True))
    op.add_column('design', sa.Column('barcode_direction', sa.Integer(), nullable=True))
    op.add_column('design', sa.Column('mirror', sa.Integer(), nullable=True))
    op.add_column('design', sa.Column('flip', sa.String(length=10), nullable=True))
    op.add_column('design', sa.Column('layers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design', 'layers')
    op.drop_column('design', 'flip')
    op.drop_column('design', 'mirror')
    op.drop_column('design', 'barcode_direction')
    op.drop_column('design', 'guillotine_packing')
    # ### end Alembic commands ###
