"""V1.3.0: 新增路由表

Revision ID: 663feb777b7a
Revises: 2c2a6d1c7e0c
Create Date: 2022-07-19 15:33:32.046432

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '663feb777b7a'
down_revision = '2c2a6d1c7e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table(
        'routes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('path', sa.String(length=50), nullable=False, comment='路径'),
        sa.Column(
            'project_type',
            sa.Enum('DPT', 'PP', name='projecttype'),
            nullable=True,
            comment='项目类型'
        ),
        sa.Column(
            'name',
            sa.String(length=20),
            nullable=False,
            comment='名称'
        ),
        sa.PrimaryKeyConstraint('id'),
        mysql_charset='utf8'
    )
    op.create_index(op.f('ix_routes_path'), 'routes', ['path'], unique=False)

    default_records = [
        {
            "id": 1,
            "path": "task",
            "project_type": None,
            "name": "HEADER.TASK_STATE",
        },
        {
            "id": 2,
            "path": "pallet",
            "project_type": "dpt",
            "name": "HEADER.PALLET_PLAN",
        },
        {
            "id": 3,
            "path": "box-register",
            "project_type": "dpt",
            "name": "HEADER.BOX_REGISTER",
        },
        {
            "id": 4,
            "path": 'log',
            "project_type": None,
            "name": 'HEADER.NODE_LOG',
        },
        {
            "id": 5,
            "path": "task-history",
            "project_type": None,
            "name": "HEADER.TASK_INFO",
        },
        {
            "id": 6,
            "path": "custom",
            "project_type": None,
            "name": "HEADER.CUSTOM"
        }
    ]
    op.bulk_insert(table, default_records)
    # ### end Alembic commands ###


def downgrade():
    op.drop_index(op.f('ix_routes_path'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
