"""V1.3.0: 垛型表新增垛型图片链接字段

Revision ID: 69d00488cb23
Revises: 663feb777b7a
Create Date: 2022-07-29 15:34:54.901113

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '69d00488cb23'
down_revision = '663feb777b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'design',
        sa.Column(
            'image_url',
            sa.String(length=100),
            nullable=True,
            comment='垛型图片链接'
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design', 'image_url')
    # ### end Alembic commands ###
