"""V1.3.0: 新增异常记录表

Revision ID: 93ae756e6711
Revises: 663feb777b7a
Create Date: 2022-08-01 14:53:02.591247

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '93ae756e6711'
down_revision = '69d00488cb23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'error_records',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'error_code',
            sa.String(length=20),
            nullable=True,
            comment='异常状态码'
        ),
        sa.Column(
            'error_source',
            sa.Enum('XTF', 'VISION', name='errorsources'),
            nullable=True,
            comment='异常来源'
        ),
        sa.Column(
            'order_id',
            sa.String(length=50),
            nullable=True,
            comment='订单编号'
        ),
        sa.Column(
            'task_id',
            sa.String(length=50),
            nullable=True,
            comment='任务编号'
        ),
        sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
        sa.PrimaryKeyConstraint('id'),
        mysql_charset='utf8'
    )
    op.create_index(
        op.f('ix_error_records_create_time'),
        'error_records',
        ['create_time'],
        unique=False
    )
    op.create_index(
        op.f('ix_error_records_task_id'),
        'error_records',
        ['task_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_records_task_id'), table_name='error_records')
    op.drop_index(
        op.f('ix_error_records_create_time'),
        table_name='error_records'
    )
    op.drop_table('error_records')
    # ### end Alembic commands ###
