"""V1.3.1: `box.scan_code` 长度改为 64

Revision ID: d28c3b51eb54
Revises: 93ae756e6711
Create Date: 2022-08-18 14:46:28.797966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "d28c3b51eb54"
down_revision = "93ae756e6711"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "box",
        "scan_code",
        existing_type=mysql.VARCHAR(length=30),
        type_=sa.String(length=64),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "box",
        "scan_code",
        existing_type=sa.String(length=64),
        type_=mysql.VARCHAR(length=30),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
