"""V1.3.1: `design.pallet_id` 和 `design.box_id` 不能为 null

Revision ID: edab5bcb4267
Revises: d28c3b51eb54
Create Date: 2022-08-20 11:29:35.040187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "edab5bcb4267"
down_revision = "d28c3b51eb54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "design", "pallet_id", existing_type=mysql.INTEGER(), nullable=False
    )
    op.alter_column("design", "box_id", existing_type=mysql.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("design", "box_id", existing_type=mysql.INTEGER(), nullable=True)
    op.alter_column("design", "pallet_id", existing_type=mysql.INTEGER(), nullable=True)
    # ### end Alembic commands ###
