"""V1.4.0: design 表新增 `is_del` 字段，用于标记是否已删除.

Revision ID: 3a34e1624e79
Revises: d28c3b51eb54
Create Date: 2022-08-24 09:23:27.526608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
down_revision = "edab5bcb4267"
revision = "3a34e1624e79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "box", sa.Column("batch_no", sa.String(length=32), nullable=True, comment="批次号")
    )
    op.add_column(
        "design",
        sa.Column("batch_no", sa.String(length=32), nullable=True, comment="批次号"),
    )
    op.add_column(
        "design",
        sa.Column(
            "create_time",
            sa.DateTime(),
            server_default=sa.text("NOW()"),
            nullable=True,
            comment="创建时间",
        ),
    )
    op.add_column(
        "design",
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="上次更新时间"),
    )
    op.add_column(
        "design", sa.Column("is_del", sa.BOOLEAN(), default=False, nullable=True, comment="是否已删除")
    )
    op.alter_column(
        "design",
        "layers",
        existing_type=mysql.INTEGER(),
        comment="层数",
        existing_nullable=True,
    )
    op.alter_column(
        "design",
        "layout",
        existing_type=mysql.JSON(),
        comment="规划数据",
        existing_nullable=True,
    )
    op.drop_index("name", table_name="design")
    op.create_unique_constraint("uniq_name_is_del", "design", ["name", "is_del"])
    # 更新已有数据的 `is_del` 字段为 `False`
    op.execute("UPDATE design SET is_del = 0;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uniq_name_is_del", "design", type_="unique")
    op.create_index("name", "design", ["name"], unique=False)
    op.alter_column(
        "design",
        "layout",
        existing_type=mysql.JSON(),
        comment=None,
        existing_comment="规划数据",
        existing_nullable=True,
    )
    op.alter_column(
        "design",
        "layers",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="层数",
        existing_nullable=True,
    )
    op.drop_column("design", "is_del")
    op.drop_column("design", "update_time")
    op.drop_column("design", "create_time")
    op.drop_column("design", "batch_no")
    op.drop_column("box", "batch_no")
    # ### end Alembic commands ###
