"""V1.4.0: error records 新增 `task` 字段

Revision ID: bcd63de5b3ab
Revises: 3a34e1624e79
Create Date: 2022-08-30 14:24:45.175215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "bcd63de5b3ab"
down_revision = "3a34e1624e79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "error_records", sa.Column("task", sa.JSON(), nullable=True, comment="任务快照")
    )
    op.add_column(
        "error_records", sa.Column("error_msg", sa.String(255), nullable=True, comment="异常消息")
    )
    op.add_column(
        "error_records", sa.Column("tip", sa.String(255), nullable=True, comment="异常提示")
    )
    op.drop_index("ix_error_records_task_id", table_name="error_records")
    op.drop_column("error_records", "order_id")
    op.drop_column("error_records", "task_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "error_records",
        sa.Column("task_id", mysql.VARCHAR(length=50), nullable=True, comment="任务编号"),
    )
    op.add_column(
        "error_records",
        sa.Column("order_id", mysql.VARCHAR(length=50), nullable=True, comment="订单编号"),
    )
    op.create_index(
        "ix_error_records_task_id", "error_records", ["task_id"], unique=False
    )
    op.drop_column("error_records", "task")
    op.drop_column("error_records", "error_msg")
    op.drop_column("error_records", "tip")
    # ### end Alembic commands ###
