"""V1.4.0: register box 新增扩展字段

Revision ID: ab4a7bd8dcb3
Revises: 710f9f74eedb
Create Date: 2022-09-07 12:57:10.500520

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab4a7bd8dcb3"
down_revision = "287e8b3869da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dpt_register_box",
        sa.Column("extra1", sa.String(length=255), nullable=True, comment="备用字段1"),
    )
    op.add_column(
        "dpt_register_box",
        sa.Column("extra2", sa.String(length=255), nullable=True, comment="备用字段2"),
    )
    op.add_column(
        "dpt_register_box",
        sa.Column("extra3", sa.String(length=255), nullable=True, comment="备用字段3"),
    )
    op.add_column(
        "dpt_register_box",
        sa.Column("extra4", sa.String(length=255), nullable=True, comment="备用字段4"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dpt_register_box", "extra4")
    op.drop_column("dpt_register_box", "extra3")
    op.drop_column("dpt_register_box", "extra2")
    op.drop_column("dpt_register_box", "extra1")
    # ### end Alembic commands ###
