"""V1.4.0: design 新增 `objects` 字段

Revision ID: 078d4f0c6916
Revises: 3a34e1624e79
Create Date: 2022-08-25 10:50:35.334636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "078d4f0c6916"
down_revision = "ab4a7bd8dcb3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "design", sa.Column("objects", sa.JSON(), nullable=True, comment="规划数据")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("design", "objects")
    # ### end Alembic commands ###
