"""V1.4.0: box 与 pallet 表增加 `is_del` 字段, 用于标记数据是否已删除

Revision ID: 094b73202784
Revises: 078d4f0c6916
Create Date: 2022-09-14 13:30:00.950181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "094b73202784"
down_revision = "078d4f0c6916"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "box", sa.Column("is_del", sa.BOOLEAN(),default=False, nullable=True, comment="是否已删除")
    )
    op.alter_column(
        "box",
        "name",
        existing_type=mysql.VARCHAR(length=64),
        nullable=False,
        comment="箱子名称",
    )
    op.alter_column(
        "box",
        "scan_code",
        existing_type=mysql.VARCHAR(length=64),
        nullable=False,
        comment="条码",
    )
    op.drop_index("name", table_name="box")
    op.drop_index("scan_code", table_name="box")
    op.create_unique_constraint("uniq_name_is_del", "box", ["name", "is_del"])
    op.create_unique_constraint("uniq_scan_code_is_del", "box", ["scan_code", "is_del"])
    op.add_column(
        "pallet", sa.Column("is_del", sa.BOOLEAN(), default=False, nullable=True, comment="是否已删除")
    )
    op.alter_column(
        "pallet",
        "name",
        existing_type=mysql.VARCHAR(length=64),
        nullable=False,
        comment="托盘名称",
    )
    op.drop_index("name", table_name="pallet")
    op.create_unique_constraint("uniq_name_is_del", "pallet", ["name", "is_del"])
    # 更新已有数据的 `is_del` 字段为 `False`
    op.execute("UPDATE box SET is_del = 0;")
    op.execute("UPDATE pallet SET is_del = 0;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uniq_name_is_del", "pallet", type_="unique")
    op.create_index("name", "pallet", ["name"], unique=False)
    op.alter_column(
        "pallet",
        "name",
        existing_type=mysql.VARCHAR(length=64),
        nullable=True,
        comment=None,
        existing_comment="托盘名称",
    )
    op.drop_column("pallet", "is_del")
    op.drop_constraint("uniq_scan_code_is_del", "box", type_="unique")
    op.drop_constraint("uniq_name_is_del", "box", type_="unique")
    op.create_index("scan_code", "box", ["scan_code"], unique=False)
    op.create_index("name", "box", ["name"], unique=False)
    op.alter_column(
        "box",
        "scan_code",
        existing_type=mysql.VARCHAR(length=64),
        nullable=True,
        comment=None,
        existing_comment="条码",
    )
    op.alter_column(
        "box",
        "name",
        existing_type=mysql.VARCHAR(length=64),
        nullable=True,
        comment=None,
        existing_comment="箱子名称",
    )
    op.drop_column("box", "is_del")
    # ### end Alembic commands ###
