"""V1.5.0: routes 表格中新增两条数据，用于展示自定义功能标签栏

Revision ID: d9fca3ded8fc
Revises: 094b73202784
Create Date: 2022-10-09 10:42:35.334636

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "d9fca3ded8fc"
down_revision = "094b73202784"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO routes VALUES (9, 'custom-ui', 'DPT', 'HEADER.CUSTOM_UI'), (10, 'custom-ui', 'PP', 'HEADER.CUSTOM_UI');")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM routes WHERE id in (9,10);")
    # ### end Alembic commands ###
