"""V1.5.0: 修改日志表部分字段的数据类型.

Revision ID: ed4f6722f192
Revises: a726a57f1190
Create Date: 2022-10-28 13:40:58.496339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ed4f6722f192"
down_revision = "a726a57f1190"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "log",
        "zh_msg",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "log",
        "en_msg",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "log",
        "ja_msg",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "log",
        "zh_tip",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "log",
        "en_tip",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "log",
        "ja_tip",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column('error_records', 'error_msg',
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_comment='异常消息',
        existing_nullable=True)
    op.alter_column('error_records', 'tip',
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_comment='异常提示',
        existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "log",
        "ja_tip",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "log",
        "en_tip",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "log",
        "zh_tip",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "log",
        "ja_msg",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "log",
        "en_msg",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "log",
        "zh_msg",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column('error_records', 'tip',
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_comment='异常提示',
        existing_nullable=True)
    op.alter_column('error_records', 'error_msg',
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_comment='异常消息',
        existing_nullable=True)
    # ### end Alembic commands ###
