"""V1.6.0: routes 新增工业自定义页面路由

Revision ID: 93e08aaf5918
Revises: ed4f6722f192
Create Date: 2022-11-22 10:42:35.334636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "93e08aaf5918"
down_revision = "ed4f6722f192"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routes', 'project_type',
            existing_type=mysql.ENUM('DPT', 'PP'),
            type_=sa.Enum('DPT', 'PP', 'IND', name='projecttype'),
            existing_comment='项目类型',
            existing_nullable=True)
    op.execute("insert into routes values(11, 'custom-ui', 'IND', 'HEADER.CUSTOM_UI');")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routes', 'project_type',
            existing_type=sa.Enum('DPT', 'PP', name='projecttype'),
            type_=mysql.ENUM('DPT', 'PP'),
            existing_comment='项目类型',
            existing_nullable=True)
    op.execute("DELETE FROM routes WHERE id = 11;")
    # ### end Alembic commands ###
