"""empty message

Revision ID: bfa53230e088
Revises: 93e08aaf5918
Create Date: 2022-12-14 17:32:12.817324

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bfa53230e088'
down_revision = '93e08aaf5918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("insert into routes values(12, 'custom', 'IND', 'HEADER.CUSTOM');")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM routes WHERE id = 12;")
    # ### end Alembic commands ###
