"""更新枚举字段

Revision ID: 96fa9ca50484
Revises: 9734b714a57d
Create Date: 2022-11-02 16:59:24.581593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "96fa9ca50484"
down_revision = "9734b714a57d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wcs_history_orders",
        "order_status",
        existing_type=mysql.ENUM(
            "PENDING", "UNSTARTED", "STARTED", "FINISHED", "ERROR", "TERMINATED"
        ),
        type_=sa.Enum(
            "PENDING",
            "UNSTARTED",
            "STARTED",
            "FINISHED",
            "ERROR",
            "TERMINATED",
            "ENDED",
            name="taskstatus",
        ),
        existing_comment="订单状态",
        existing_nullable=True,
    )
    op.alter_column(
        "wcs_history_tasks",
        "task_type",
        existing_type=mysql.ENUM(
            "SINGLE_DEPAL",
            "SINGLE_PAL",
            "MULTI_DEPAL",
            "MULTI_PAL_ONLINE",
            "MULTI_PAL_OFFLINE",
            "PP_DEFAULT",
            "PP_CYCLE",
            "DEMO",
        ),
        type_=sa.Enum(
            "SINGLE_DEPAL",
            "SINGLE_PAL",
            "MULTI_DEPAL",
            "MULTI_PAL_ONLINE",
            "MULTI_PAL_OFFLINE",
            "PP_DEFAULT",
            "PP_CYCLE",
            name="tasktype",
        ),
        existing_comment="任务类型",
        existing_nullable=True,
    )
    op.alter_column(
        "wcs_history_tasks",
        "task_status",
        existing_type=mysql.ENUM(
            "PENDING", "UNSTARTED", "STARTED", "FINISHED", "ERROR", "TERMINATED"
        ),
        type_=sa.Enum(
            "PENDING",
            "UNSTARTED",
            "STARTED",
            "FINISHED",
            "ERROR",
            "TERMINATED",
            "ENDED",
            name="taskstatus",
        ),
        existing_comment="任务状态",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wcs_history_tasks",
        "task_status",
        existing_type=sa.Enum(
            "PENDING",
            "UNSTARTED",
            "STARTED",
            "FINISHED",
            "ERROR",
            "TERMINATED",
            "ENDED",
            name="taskstatus",
        ),
        type_=mysql.ENUM(
            "PENDING", "UNSTARTED", "STARTED", "FINISHED", "ERROR", "TERMINATED"
        ),
        existing_comment="任务状态",
        existing_nullable=True,
    )
    op.alter_column(
        "wcs_history_tasks",
        "task_type",
        existing_type=sa.Enum(
            "SINGLE_DEPAL",
            "SINGLE_PAL",
            "MULTI_DEPAL",
            "MULTI_PAL_ONLINE",
            "MULTI_PAL_OFFLINE",
            "PP_DEFAULT",
            "PP_CYCLE",
            name="tasktype",
        ),
        type_=mysql.ENUM(
            "SINGLE_DEPAL",
            "SINGLE_PAL",
            "MULTI_DEPAL",
            "MULTI_PAL_ONLINE",
            "MULTI_PAL_OFFLINE",
            "PP_DEFAULT",
            "PP_CYCLE",
            "DEMO",
        ),
        existing_comment="任务类型",
        existing_nullable=True,
    )
    op.alter_column(
        "wcs_history_orders",
        "order_status",
        existing_type=sa.Enum(
            "PENDING",
            "UNSTARTED",
            "STARTED",
            "FINISHED",
            "ERROR",
            "TERMINATED",
            "ENDED",
            name="taskstatus",
        ),
        type_=mysql.ENUM(
            "PENDING", "UNSTARTED", "STARTED", "FINISHED", "ERROR", "TERMINATED"
        ),
        existing_comment="订单状态",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
