"""empty message

Revision ID: 6eb1fca9ae5f
Revises: 96fa9ca50484
Create Date: 2023-12-04 10:07:30.044659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6eb1fca9ae5f'
down_revision = '96fa9ca50484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pallet_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('current_direction', sa.String(length=50), nullable=True, comment='当前拣配托盘朝向'),
    sa.Column('pallet_tote_data', sa.JSON(), nullable=True, comment='拣配托盘上物料信息'),
    sa.Column('pick_tote_data', sa.JSON(), nullable=True, comment='需要抓取的物料信息'),
    sa.Column('cache_pallet_tote_data', sa.JSON(), nullable=True, comment='缓存托盘上物料信息'),
    sa.Column('path', sa.JSON(), nullable=True, comment='路径'),
    sa.Column('pallet_tote_data_2', sa.JSON(), nullable=True, comment='笼车托盘2上的物料信息'),
    sa.Column('pallet_tote_data_3', sa.JSON(), nullable=True, comment='笼车托盘3上的物料信息'),
    sa.Column('pallet_tote_data_7', sa.JSON(), nullable=True, comment='混码缓存区7上的物料信息'),
    sa.Column('pallet_tote_data_8', sa.JSON(), nullable=True, comment='混码缓存区8上的物料信息'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.drop_index('uniq_order_is_del', table_name='planning_result')
    op.drop_table('planning_result')

    op.alter_column('wcs_history_orders', 'order_status',
               existing_type=mysql.ENUM('PENDING', 'UNSTARTED', 'STARTED', 'FINISHED', 'ERROR', 'TERMINATED', 'ENDED'),
               type_=sa.Enum('PENDING', 'UNSTARTED', 'STARTED', 'DEPALFINISHED','CHANGE_180','FINISHED', 'ERROR', 'TERMINATED', 'ENDED', name='taskstatus'),
               existing_comment='订单状态',
               existing_nullable=True)
    op.alter_column('wcs_history_tasks', 'task_type',
               existing_type=mysql.ENUM('SINGLE_DEPAL', 'SINGLE_PAL', 'MULTI_DEPAL', 'MULTI_PAL_ONLINE', 'MULTI_PAL_OFFLINE', 'PP_DEFAULT', 'PP_CYCLE'),
               type_=sa.Enum('SINGLE_DEPAL', 'SINGLE_PAL', 'MULTI_DEPAL', 'MULTI_PAL_ONLINE', 'MULTI_PAL_OFFLINE', 'MERGE_TASK', 'PP_DEFAULT', 'PP_CYCLE', name='tasktype'),
               existing_comment='任务类型',
               existing_nullable=True)
    op.alter_column('wcs_history_tasks', 'task_status',
               existing_type=mysql.ENUM('PENDING', 'UNSTARTED', 'STARTED', 'FINISHED', 'ERROR', 'TERMINATED', 'ENDED'),
               type_=sa.Enum('PENDING', 'UNSTARTED', 'STARTED', 'DEPALFINISHED','CHANGE_180','FINISHED', 'ERROR', 'TERMINATED', 'ENDED', name='taskstatus'),
               existing_comment='任务状态',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wcs_history_tasks', 'task_status',
               existing_type=sa.Enum('PENDING', 'UNSTARTED', 'STARTED', 'DEPALFINISHED','CHANGE_180', 'FINISHED', 'ERROR', 'TERMINATED', 'ENDED', name='taskstatus'),
               type_=mysql.ENUM('PENDING', 'UNSTARTED', 'STARTED', 'FINISHED', 'ERROR', 'TERMINATED', 'ENDED'),
               existing_comment='任务状态',
               existing_nullable=True)
    op.alter_column('wcs_history_tasks', 'task_type',
               existing_type=sa.Enum('SINGLE_DEPAL', 'SINGLE_PAL', 'MULTI_DEPAL', 'MULTI_PAL_ONLINE', 'MULTI_PAL_OFFLINE', 'MERGE_TASK', 'PP_DEFAULT', 'PP_CYCLE', name='tasktype'),
               type_=mysql.ENUM('SINGLE_DEPAL', 'SINGLE_PAL', 'MULTI_DEPAL', 'MULTI_PAL_ONLINE', 'MULTI_PAL_OFFLINE', 'PP_DEFAULT', 'PP_CYCLE'),
               existing_comment='任务类型',
               existing_nullable=True)
    op.alter_column('wcs_history_orders', 'order_status',
               existing_type=sa.Enum('PENDING', 'UNSTARTED', 'STARTED', 'DEPALFINISHED','CHANGE_180', 'FINISHED', 'ERROR', 'TERMINATED', 'ENDED', name='taskstatus'),
               type_=mysql.ENUM('PENDING', 'UNSTARTED', 'STARTED', 'FINISHED', 'ERROR', 'TERMINATED', 'ENDED'),
               existing_comment='订单状态',
               existing_nullable=True)

    op.create_table('planning_result',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=100), nullable=False, comment='订单ID'),
    sa.Column('status', mysql.ENUM('PENDING', 'PLANNING', 'FINISHED', 'FAIL'), nullable=False, comment='规划状态'),
    sa.Column('result', mysql.JSON(), nullable=True, comment='规划结果'),
    sa.Column('start_time', mysql.DATETIME(), nullable=True, comment='开始规划的时间'),
    sa.Column('end_time', mysql.DATETIME(), nullable=True, comment='结束的时间'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否已删除'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uniq_order_is_del', 'planning_result', ['order_id', 'is_deleted'], unique=False)
    op.drop_table('pallet_data')
    # ### end Alembic commands ###
