"""empty message

Revision ID: 8ed4e87bc7e6
Revises: 6eb1fca9ae5f
Create Date: 2024-11-01 13:51:17.092505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ed4e87bc7e6'
down_revision = '6eb1fca9ae5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cage_layer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('layer_num', sa.Integer(), nullable=True, comment='中欧笼车层数'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.alter_column('pallet_data', 'pallet_tote_data_7',
               existing_type=mysql.JSON(),
               comment='混码缓存区7上的物料信息',
               existing_nullable=True)
    op.alter_column('pallet_data', 'pallet_tote_data_8',
               existing_type=mysql.JSON(),
               comment='混码缓存区8上的物料信息',
               existing_nullable=True)
    op.alter_column('wcs_history_orders', 'order_status',
               existing_type=mysql.ENUM('PENDING', 'UNSTARTED', 'STARTED', 'DEPALFINISHED', 'CHANGE_180', 'FINISHED', 'ERROR', 'TERMINATED', 'ENDED'),
               type_=sa.Enum('PENDING', 'UNSTARTED', 'STARTED', 'DEPALFINISHED', 'CHANGE_180', 'MULTI_NORMAL', 'MULTI_CACHE', 'FINISHED', 'ERROR', 'TERMINATED', 'ENDED', name='taskstatus'),
               existing_comment='订单状态',
               existing_nullable=True)
    op.alter_column('wcs_history_tasks', 'task_status',
               existing_type=mysql.ENUM('PENDING', 'UNSTARTED', 'STARTED', 'DEPALFINISHED', 'CHANGE_180', 'FINISHED', 'ERROR', 'TERMINATED', 'ENDED'),
               type_=sa.Enum('PENDING', 'UNSTARTED', 'STARTED', 'DEPALFINISHED', 'CHANGE_180', 'MULTI_NORMAL', 'MULTI_CACHE', 'FINISHED', 'ERROR', 'TERMINATED', 'ENDED', name='taskstatus'),
               existing_comment='任务状态',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wcs_history_tasks', 'task_status',
               existing_type=sa.Enum('PENDING', 'UNSTARTED', 'STARTED', 'DEPALFINISHED', 'CHANGE_180', 'MULTI_NORMAL', 'MULTI_CACHE', 'FINISHED', 'ERROR', 'TERMINATED', 'ENDED', name='taskstatus'),
               type_=mysql.ENUM('PENDING', 'UNSTARTED', 'STARTED', 'DEPALFINISHED', 'CHANGE_180', 'FINISHED', 'ERROR', 'TERMINATED', 'ENDED'),
               existing_comment='任务状态',
               existing_nullable=True)
    op.alter_column('wcs_history_orders', 'order_status',
               existing_type=sa.Enum('PENDING', 'UNSTARTED', 'STARTED', 'DEPALFINISHED', 'CHANGE_180', 'MULTI_NORMAL', 'MULTI_CACHE', 'FINISHED', 'ERROR', 'TERMINATED', 'ENDED', name='taskstatus'),
               type_=mysql.ENUM('PENDING', 'UNSTARTED', 'STARTED', 'DEPALFINISHED', 'CHANGE_180', 'FINISHED', 'ERROR', 'TERMINATED', 'ENDED'),
               existing_comment='订单状态',
               existing_nullable=True)
    op.alter_column('pallet_data', 'pallet_tote_data_8',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='混码缓存区8上的物料信息',
               existing_nullable=True)
    op.alter_column('pallet_data', 'pallet_tote_data_7',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='混码缓存区7上的物料信息',
               existing_nullable=True)
    op.drop_table('cage_layer')
    # ### end Alembic commands ###
