"""empty message

Revision ID: fde73082bf93
Revises: 3944ba46cf52
Create Date: 2024-11-01 11:44:47.258291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fde73082bf93'
down_revision = '3944ba46cf52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cage_layer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('layer_num', sa.Integer(), nullable=True, comment='中欧笼车层数'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cage_layer')
    # ### end Alembic commands ###
